# spring.application.name=medvalt
# spring.datasource.url=jdbc:mysql://localhost:3306/medvault
# spring.datasource.username=root
# spring.datasource.password=Mohanreddysomu@2005
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.application.name=medvalt

# Supabase Postgres connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.gsaqgzcfnoerolcbykwa
spring.datasource.password=MohanMedvault@2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=ThisIsASuperLongRandomSecretKeyForHS256Algorithm123456

gemini.api.key=AIzaSyBVa_pjIXIDpj7BuVfAGkIc0Grxb5YCPU4

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=somumohanreddy@gmail.com
spring.mail.password=fppnqddmiwfkbneq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000